CONSUMER_KEY:
CONSUMER_SECRET:
OAUTH_MWURI: https://meta.wikimedia.org/w
SESSION_COOKIE_NAME: wikifile-transfer
SESSION_COOKIE_PATH: /wikifile-transfer
SESSION_COOKIE_SECURE: True
SESSION_REFRESH_EACH_REQUEST: False
PREFERRED_URL_SCHEME: https
SQLALCHEMY_DATABASE_URI: mysql+pymysql://root:@localhost/wikifile
SQLALCHEMY_TRACK_MODIFICATIONS: False